# Generated by Django 3.1.6 on 2021-02-24 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0002_auto_20210224_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.ImageField(default='abc', upload_to='pics'),
            preserve_default=False,
        ),
    ]
