# Generated by Django 3.0.13 on 2021-02-25 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0003_article_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='img',
        ),
    ]
